export const VIEWPORT_HEIGHT = 384; // h-96
export const HIT_LINE_Y = VIEWPORT_HEIGHT - 8;
export const NOTE_WIDTH_RATIO = 0.85; // proportion of note width compared to key width
export const NOTE_GAP_PX = 2; // defines the gap between notes on same column
export const PX_PER_SEC = 120;
export const PX_PER_MS = PX_PER_SEC / 1000;
export const viewportMs = VIEWPORT_HEIGHT / PX_PER_MS;
export const NOTE_GAP_MS = NOTE_GAP_PX / PX_PER_MS;
export const PERCENTAGES = [25, 50, 75, 100, 125, 150, 175]; // bpm percentages multiplier
export const ARROW_KEY_STEP_MS = 50;
